bcrsilva/fornecedor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^novo/$', views.novo_fornecedor, name='novo_fornecedor'),
    url(r'^editar/(?P<pk>\d+)/$', views.editar_fornecedor, name='editar_fornecedor'),
    url(r'^excluir/(?P<pk>\d+)/$', views.excluir_fornecedor,
        name='excluir_fornecedor'),
]

bcrsilva/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bcrsilva.core.urls', namespace="core")),
    url(r'^cliente/', include('bcrsilva.cliente.urls', namespace="cliente")),
    url(r'^produto/', include('bcrsilva.produto.urls', namespace="produto")),
    url(r'^fornecedor/', include('bcrsilva.fornecedor.urls', namespace="fornecedor")),
    url(r'^estoque/', include('bcrsilva.estoque.urls', namespace="estoque")),
    url(r'^admin/', include(admin.site.urls)),
]

bcrsilva/fornecedor/models.py
# from django.db import models
from bcrsilva.core.models import PessoaJuridica


class Fornecedor(PessoaJuridica):
    def __str__(self):
        return '%s - %s' % (self.razao_social, self.nome_fantasia)

    class Meta:
        verbose_name = 'Fornecedor'
        verbose_name_plural = 'Fornecedores'
        ordering = ['razao_social']

bcrsilva/fornecedor/forms.py
from django import forms
from .models import Fornecedor


class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = [
            'razao_social', 'nome_fantasia', 'cnpj', 'inscricao_estadual',
            'cep', 'endereco', 'numero', 'bairro', 'cidade', 'uf'
        ]

        widgets = {
            'razao_social': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a Razão Social'
                }
            ),
            'nome_fantasia': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o Nome Fantasia'
                }
            ),
            'cnpj': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o CNPJ'
                }
            ),
            'inscricao_estadual': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a Inscrição Estadual'
                }
            ),
            'cep': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            ),
            'endereco': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o endereço',
                    'style': 'resize: none',
                    'rows': 1
                }
            ),
            'numero': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            ),
            'bairro': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o bairro'
                }
            ),
            'cidade': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a cidade'
                }
            ),
            'uf': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            )
        }

bcrsilva/fornecedor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from datetime import datetime
from .models import Fornecedor
from .forms import FornecedorForm
from bcrsilva.core.models import Contato
from bcrsilva.core.forms import ContatoInlineFormSet


def home(request):
    atualizado_em = datetime.now()
    fornecedores = Fornecedor.objects.all()
    template_name = 'fornecedor/home.html'
    context = {
        'fornecedores': fornecedores,
        'atualizado_em': atualizado_em
    }
    return render(request, template_name, context)


def novo_fornecedor(request):
    form = FornecedorForm()
    contato_forms = ContatoInlineFormSet(
        queryset=Contato.objects.none()
    )

    if request.method == "POST":
        form = FornecedorForm(request.POST)
        contato_forms = ContatoInlineFormSet(
            request.POST,
            queryset=Contato.objects.none()
        )
        if form.is_valid() and contato_forms.is_valid():
            fornecedor = form.save(commit=False)
            fornecedor.save()
            contatos = contato_forms.save(commit=False)
            for contato in contatos:
                contato.pessoa = fornecedor
                contato.save()
            messages.success(request, 'Fornecedor salvo com sucesso!')
            return redirect('fornecedor:home')
    template_name = 'fornecedor/editar_fornecedor.html'
    context = {
        'form': form,
        'formset': contato_forms,
        'title': 'Registrar fornecedor'
    }
    return render(request, template_name, context)


def editar_fornecedor(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)
    form = FornecedorForm(instance=fornecedor)
    contato_forms = ContatoInlineFormSet(
        queryset=form.instance.contatos.all()
    )

    if request.method == "POST":
        form = FornecedorForm(request.POST, instance=fornecedor)
        contato_forms = ContatoInlineFormSet(
            request.POST,
            queryset=form.instance.contatos.all()
        )
        if form.is_valid() and contato_forms.is_valid():
            form.save()
            instances = contato_forms.save(commit=False)
            for obj in instances:
                obj.pessoa = fornecedor
                obj.save()
            for obj in contato_forms.deleted_objects:
                obj.delete()
            messages.success(request, 'Fornecedor alterado com sucesso!')
            return redirect('fornecedor:home')
    template_name = 'fornecedor/editar_fornecedor.html'
    context = {
        'form': form,
        'formset': contato_forms,
        'title': 'Editar fornecedor: "%s"' % (fornecedor)
    }
    return render(request, template_name, context)


def excluir_fornecedor(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)

    if request.method == "POST":
        fornecedor.delete()
        messages.success(request, 'Fornecedor excluído com sucesso!')
        return redirect('fornecedor:home')
    template_name = 'confirmar_delete.html'
    context = {
        'objeto': fornecedor,
        'title': 'Excluir fornecedor',
        'mensagem': 'Tem certeza que quer deletar o Fornecedor: ',
        'fornecedor': True
    }
    return render(request, template_name, context)

bcrsilva/fornecedor/templates/fornecedor/editar_fornecedor.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <div class="card card-register mx-auto" style="max-width: 100%;">
    <div class="card-header"><b>{{ title }}</b></div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-row">
          <div class="form-group col-md-4">
            {{ form.razao_social.label_tag }}
            {{ form.razao_social }}
            {{ form.razao_social.errors }}
          </div>
          <div class="form-group col-md-4">
            {{ form.nome_fantasia.label_tag }}
            {{ form.nome_fantasia }}
            {{ form.nome_fantasia.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.cnpj.label_tag }}
            {{ form.cnpj }}
            {{ form.cnpj.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.inscricao_estadual.label_tag }}
            {{ form.inscricao_estadual }}
            {{ form.inscricao_estadual.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.cep.label_tag }}
            {{ form.cep }}
            {{ form.cep.errors }}
          </div>
          <div class="form-group col-md-4">
            {{ form.endereco.label_tag }}
            {{ form.endereco }}
            {{ form.endereco.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.numero.label_tag }}
            {{ form.numero }}
            {{ form.numero.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.bairro.label_tag }}
            {{ form.bairro }}
            {{ form.bairro.errors }}
          </div>
          <div class="form-group col-md-3">
            {{ form.cidade.label_tag }}
            {{ form.cidade }}
            {{ form.cidade.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.uf.label_tag }}
            {{ form.uf }}
            {{ form.uf.errors }}
          </div>
        </div>

        {{ formset.management_form }}

          <div class="card card-register mx-auto" style="max-width: 100%; margin-bottom: 1em;">
            <div class="card-header"><b>Contato(s)</b></div>
            <div class="card-body">
              <div class="form-row">
                {% for form in formset %}
                  {{ form.id }}
                  <div class="form-group" style="width: 45%; margin-right: 10px;">
                    {{ form.email.label_tag }}
  			            {{ form.email }}
  			            {{ form.email.errors }}
                  </div>
                  <div class="form-group" style="width: 45%; margin-right: 10px;">
  									{{ form.telefone.label_tag }}
  			            {{ form.telefone }}
  			            {{ form.telefone.errors }}
                  </div>
                  <div class="form-group" style="margin-top: 3%;">
                    {{ form.DELETE.label }}
                    {{ form.DELETE }}
                    <!-- <a style="border: none; margin-top: 2em;" class="form-control" href="#"
                      title="Excluir">
                      <i class="fa fa-trash-o fa-lg"></i>
                    </a> -->
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        <button type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-secondary" href="{% url 'fornecedor:home' %}">Voltar</a>
      </form>
    </div>
  </div>
{% endblock %}

bcrsilva/fornecedor/templates/fornecedor/home.html
{% extends "base.html" %}

{% block content %}
<div class="card mb-3">
  <div class="card-header" style="height: 65px;">
    <div class="form-row" style="height: 40px;">
      <div class="form-group col-md-11" style="padding-top: 6px;">
        <i class="fa fa-table fa-lg"></i> <b>Fornecedores registrados</b>
      </div>
      <div class="form-group col-md-1" style="padding-left: 30px;">
        <a class="btn btn-success" href="{% url 'fornecedor:novo_fornecedor' %}" title="Novo fornecedor">
          <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Razão Social</th>
              <th>Nome Fantasia</th>
              <th>CNPJ</th>
              <th>Cidade</th>
              <th>Contato(s)</th>
              <th style="text-align: center; width: 13%;">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for fornecedor in fornecedores %}
              <tr>
                <td>{{ fornecedor.razao_social }}</td>
                <td>{{ fornecedor.nome_fantasia }}</td>
                <td>{{ fornecedor.cnpj }}</td>
                <td>{{ fornecedor.cidade }}</td>
                <td>
                  {% for contato in fornecedor.contatos.all %}
                    {{ contato }} <br>
                  {% endfor %}
                </td>
                <!-- <td style="text-align: center;">{{ produto.preco_anterior|default_if_none:"-" }}</td> -->
                <td>
                  <div class="container">
                    <div class="row">
                      <div class="col">
                        <a href="{% url 'fornecedor:editar_fornecedor' fornecedor.id %}"
                          title="Editar">
                          <i class="fa fa-pencil fa-lg"></i>
                        </a>
                      </div>
                      <div class="col">
                        <a href="{% url 'fornecedor:excluir_fornecedor' fornecedor.id %}"
                          title="Excluir">
                          <i class="fa fa-trash-o fa-lg"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em {{ atualizado_em }}</div>
  </div>
{% endblock %}