bcrsilva/cliente/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^pessoa-juridica$', views.listar_clientes_pj, name='listar_clientesPJ'),
    url(r'^pessoa-juridica/novo/$', views.novo_cliente_pj, name='novo_clientePJ'),
    url(r'^pessoa-juridica/editar/(?P<pk>\d+)/$',
        views.editar_cliente_pj, name='editar_clientePJ'),
    url(r'^pessoa-juridica/excluir/(?P<pk>\d+)/$',
        views.excluir_cliente_pj, name='excluir_clientePJ'),
    url(r'^pessoa-fisica$', views.listar_clientes_pf, name='listar_clientesPF'),
    url(r'^pessoa-fisica/novo/$', views.novo_cliente_pf, name='novo_clientePF'),
    url(r'^pessoa-fisica/editar/(?P<pk>\d+)/$',
        views.editar_cliente_pf, name='editar_clientePF'),
    url(r'^pessoa-fisica/excluir/(?P<pk>\d+)/$',
        views.excluir_cliente_pf, name='excluir_clientePF'),
]

bcrsilva/core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

bcrsilva/produto/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^novo/$', views.novo_produto, name='novo_produto'),
    url(r'^editar/(?P<pk>\d+)/$', views.editar_produto, name='editar_produto'),
    url(r'^excluir/(?P<pk>\d+)/$', views.excluir_produto, name='excluir_produto'),
    url(r'^categoria/$', views.lista_categorias, name="lista_categorias"),
    url(r'^categoria/(?P<pk>\d+)/$',
        views.detalhes_categoria, name='detalhes_categoria'),
    url(r'^categoria/nova/$', views.nova_categoria, name='nova_categoria'),
    url(r'^categoria/editar/(?P<pk>\d+)/$',
        views.editar_categoria, name='editar_categoria'),
    url(r'^categoria/excluir/(?P<pk>\d+)/$',
        views.excluir_categoria, name='excluir_categoria'),
]

bcrsilva/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bcrsilva.core.urls', namespace="core")),
    url(r'^cliente/', include('bcrsilva.cliente.urls', namespace="cliente")),
    url(r'^produto/', include('bcrsilva.produto.urls', namespace="produto")),
    url(r'^fornecedor/', include('bcrsilva.fornecedor.urls', namespace="fornecedor")),
    url(r'^estoque/', include('bcrsilva.estoque.urls', namespace="estoque")),
    url(r'^admin/', include(admin.site.urls)),
]

bcrsilva/core/models.py
from django.db import models


class Pessoa(models.Model):
    cep = models.CharField('CEP', max_length=8)
    endereco = models.TextField('Endereço')
    numero = models.IntegerField('Número/Lote')
    bairro = models.CharField('Bairro', max_length=100)
    cidade = models.CharField('Cidade', max_length=100)
    uf = models.CharField('UF', max_length=2)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)


class PessoaFisica(Pessoa):
    nome = models.CharField('Nome', max_length=100)
    apelido = models.CharField('Apelido', max_length=30, blank=True, null=True)
    rg = models.CharField('RG', max_length=20)
    cpf = models.CharField('CPF', max_length=11)
    data_nascimento = models.DateField('Data de nascimento')


class PessoaJuridica(Pessoa):
    razao_social = models.CharField('Razão Social', max_length=100)
    nome_fantasia = models.CharField(
        'Nome Fantasia', max_length=30, blank=True, null=True)
    cnpj = models.CharField('CNPJ', max_length=14)
    inscricao_estadual = models.CharField('Inscrição Estadual', max_length=20)


class Contato(models.Model):
    email = models.EmailField('E-mail', unique=True)
    telefone = models.CharField('Telefone', max_length=11)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)
    pessoa = models.ForeignKey(Pessoa, verbose_name='Pessoa',
                               related_name='contatos',
                               on_delete=models.CASCADE
                               )

    def __str__(self):
        return '%s - %s' % (self.email, self.telefone)

    class Meta:
        verbose_name = 'Contato'
        verbose_name_plural = 'Contatos'
        ordering = ['email']

bcrsilva/core/forms.py
from django import forms
from .models import Contato
from bcrsilva.core.models import Pessoa


class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = '__all__'


ContatoFormSet = forms.modelformset_factory(
    Contato,
    form=ContatoForm,
    extra=2
)

ContatoInlineFormSet = forms.inlineformset_factory(
    Pessoa,
    Contato,
    extra=2,
    fields=('email', 'telefone'),
    formset=ContatoFormSet,
    min_num=0,
    max_num=4,
    can_delete=True,
    widgets={
        'email': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Insira o email',
                'style': 'margin-bottom: 1em'
            }
        ),
        'telefone': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Insira o telefone',
            }
        )
    }
)

bcrsilva/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

bcrsilva/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>BCR Silva - Sistema</title>
  <!-- Bootstrap core CSS-->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'core:home' %}">
      <i class="fa fa-home" aria-hidden="true"></i> BCR Silva
    </a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-sitemap"></i>
            <span class="nav-link-text">Cadastros</span>
          </a>
          <ul class="sidenav-second-level collapse" id="collapseMulti">
            <li>
              <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMultiClientes">Clientes</a>
              <ul class="sidenav-third-level collapse" id="collapseMultiClientes">
                <li>
                  <a href="{% url 'cliente:listar_clientesPF' %}">Pessoas Físicas</a>
                </li>
                <li>
                  <a href="{% url 'cliente:listar_clientesPJ' %}">Pessoas Jurídicas</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="{% url 'fornecedor:home' %}">Fornecedores</a>
            </li>
            <li>
              <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMultiProduto">Produtos</a>
              <ul class="sidenav-third-level collapse" id="collapseMultiProduto">
                <li>
                  <a href="{% url 'produto:lista_categorias' %}">Categorias</a>
                </li>
                <li>
                  <a href="{% url 'produto:home' %}">Produtos</a>
                </li>
              </ul>
            </li>
            <li>
              <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMultiEstoque">Estoque</a>
              <ul class="sidenav-third-level collapse" id="collapseMultiEstoque">
                <li>
                  <a href="{% url 'estoque:home' %}">Notas de Entrada</a>
                </li>
{#                <li>#}
{#                  <a href="{% url 'produto:home' %}">Produtos</a>#}
{#                </li>#}
              </ul>
            </li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input class="form-control" type="text" placeholder="Buscar por...">
              <span class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Sair</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="content-wrapper">
      <div class="container-fluid">
        {% if messages %}
        <div class="alert alert-success alert-dismissable" id="success-alert">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          {% for message in messages %}
          <p>{{ message }}</p>
          {% endfor %}
        </div>
        {% endif %}
        <!-- Breadcrumbs-->
          <ol class="breadcrumb">
            {% block breadcrumb %}
              <li class="breadcrumb-item">
                <a href="{% url 'core:home' %}">Home</a>
              </li>
            {% endblock %}
            <!-- <li class="breadcrumb-item active">Tables</li> -->
          </ol>

        <div class="content">
          {% block content %}
          {% endblock %}
        </div>
      </div>

      <!-- /.content-wrapper-->
      <footer class="sticky-footer">
        <div class="container">
          <div class="text-center">
            <small>Copyright © Your Website 2018</small>
          </div>
        </div>
      </footer>
      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
      </a>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin.min.js' %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static 'js/sb-admin-datatables.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-charts.min.js' %}"></script>
    <script type="text/javascript">
      $("#success-alert").fadeTo(1000, 500).slideUp(500, function(){
        $("#success-alert").alert('close');
      });
    </script>
  </body>
  </html>

bcrsilva/core/templates/confirmar_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="card card-register mx-auto" style="max-width: 45%;">
    <div class="card-header">{{ title }}</div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <p style="padding-left: 2%;">
          {{ mensagem }} "{{ objeto }}"?
        </p>
        <div style="padding-left: 23%;">
          <button class="btn btn-danger" type="submit"><i class="fa fa-thumbs-o-up" aria-hidden="true"></i> Tenho certeza!</button>
          {% if categoria %}
            <a class="btn btn-secondary" href="{% url 'produto:lista_categorias' %}">Voltar</a>
          {% elif produto %}
            <a class="btn btn-secondary" href="{% url 'produto:home' %}">Voltar</a>
          {% elif fornecedor %}
            <a class="btn btn-secondary" href="{% url 'fornecedor:home' %}">Voltar</a>
          {% elif clientePJ %}
            <a class="btn btn-secondary" href="{% url 'cliente:listar_clientesPJ' %}">Voltar</a>
          {% elif clientePF %}
            <a class="btn btn-secondary" href="{% url 'cliente:listar_clientesPF' %}">Voltar</a>
          {% endif %}
        </div>
      </form>
    </div>
  </div>
{% endblock %}

bcrsilva/core/templates/home.html
{% extends "base.html" %}

{% block content %}
  <h1>Olá Mundo!</h1>
{% endblock %}