bcrsilva/cliente/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^pessoa-juridica$', views.listar_clientes_pj, name='listar_clientesPJ'),
    url(r'^pessoa-juridica/novo/$', views.novo_cliente_pj, name='novo_clientePJ'),
    url(r'^pessoa-juridica/editar/(?P<pk>\d+)/$',
        views.editar_cliente_pj, name='editar_clientePJ'),
    url(r'^pessoa-juridica/excluir/(?P<pk>\d+)/$',
        views.excluir_cliente_pj, name='excluir_clientePJ'),
    url(r'^pessoa-fisica$', views.listar_clientes_pf, name='listar_clientesPF'),
    url(r'^pessoa-fisica/novo/$', views.novo_cliente_pf, name='novo_clientePF'),
    url(r'^pessoa-fisica/editar/(?P<pk>\d+)/$',
        views.editar_cliente_pf, name='editar_clientePF'),
    url(r'^pessoa-fisica/excluir/(?P<pk>\d+)/$',
        views.excluir_cliente_pf, name='excluir_clientePF'),
]

bcrsilva/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bcrsilva.core.urls', namespace="core")),
    url(r'^cliente/', include('bcrsilva.cliente.urls', namespace="cliente")),
    url(r'^produto/', include('bcrsilva.produto.urls', namespace="produto")),
    url(r'^fornecedor/', include('bcrsilva.fornecedor.urls', namespace="fornecedor")),
    url(r'^estoque/', include('bcrsilva.estoque.urls', namespace="estoque")),
    url(r'^admin/', include(admin.site.urls)),
]

bcrsilva/cliente/models.py
# from django.db import models
from bcrsilva.core.models import PessoaJuridica, PessoaFisica


class ClientePJ(PessoaJuridica):
    def __str__(self):
        return '%s - %s' % (self.razao_social, self.nome_fantasia)

    class Meta:
        verbose_name = 'Cliente (PJ)'
        verbose_name_plural = 'Clientes (PJ)'
        ordering = ['razao_social']


class ClientePF(PessoaFisica):
    def __str__(self):
        return '%s - %s' % (self.nome, self.apelido)

    class Meta:
        verbose_name = 'Cliente (PF)'
        verbose_name_plural = 'Clientes (PF)'
        ordering = ['nome']

bcrsilva/cliente/forms.py
from django import forms
from .models import ClientePJ, ClientePF


class ClientePJForm(forms.ModelForm):
    class Meta:
        model = ClientePJ
        fields = [
            'razao_social', 'nome_fantasia', 'cnpj', 'inscricao_estadual',
            'cep', 'endereco', 'numero', 'bairro', 'cidade', 'uf'
        ]

        widgets = {
            'razao_social': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a Razão Social'
                }
            ),
            'nome_fantasia': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o Nome Fantasia'
                }
            ),
            'cnpj': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o CNPJ'
                }
            ),
            'inscricao_estadual': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a Inscrição Estadual'
                }
            ),
            'cep': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            ),
            'endereco': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o endereço',
                    'style': 'resize: none',
                    'rows': 1
                }
            ),
            'numero': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            ),
            'bairro': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o bairro'
                }
            ),
            'cidade': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a cidade'
                }
            ),
            'uf': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            )
        }


class ClientePFForm(forms.ModelForm):
    class Meta:
        model = ClientePF
        fields = [
            'nome', 'apelido', 'cpf', 'rg', 'data_nascimento',
            'cep', 'endereco', 'numero', 'bairro', 'cidade', 'uf'
        ]

        widgets = {
            'nome': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o nome'
                }
            ),
            'apelido': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o apelido'
                }
            ),
            'cpf': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o CPF'
                }
            ),
            'rg': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o RG'
                }
            ),
            'data_nascimento': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a data'
                }
            ),
            'cep': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            ),
            'endereco': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o endereço',
                    'style': 'resize: none',
                    'rows': 1
                }
            ),
            'numero': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            ),
            'bairro': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o bairro'
                }
            ),
            'cidade': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira a cidade'
                }
            ),
            'uf': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira'
                }
            )
        }

bcrsilva/cliente/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from datetime import datetime
from .models import ClientePJ, ClientePF
from .forms import ClientePJForm, ClientePFForm
from bcrsilva.core.models import Contato
from bcrsilva.core.forms import ContatoInlineFormSet


def listar_clientesPJ(request):
    atualizado_em = datetime.now()
    clientes = ClientePJ.objects.all()
    template_name = 'cliente/listar_clientesPJ.html'
    context = {
        'clientes': clientes,
        'atualizado_em': atualizado_em
    }
    return render(request, template_name, context)


def novo_clientePJ(request):
    form = ClientePJForm()
    contato_forms = ContatoInlineFormSet(
        queryset=Contato.objects.none()
    )

    if request.method == "POST":
        form = ClientePJForm(request.POST)
        contato_forms = ContatoInlineFormSet(
            request.POST,
            queryset=Contato.objects.none()
        )
        if form.is_valid() and contato_forms.is_valid():
            clientePJ = form.save(commit=False)
            clientePJ.save()
            contatos = contato_forms.save(commit=False)
            for contato in contatos:
                contato.pessoa = clientePJ
                contato.save()
            messages.success(request, 'Cliente(PJ) salvo com sucesso!')
            return redirect('cliente:listar_clientesPJ')
    template_name = 'cliente/editar_clientePJ.html'
    context = {
        'form': form,
        'formset': contato_forms,
        'title': 'Registrar cliente (PJ)'
    }
    return render(request, template_name, context)


def editar_clientePJ(request, pk):
    clientePJ = get_object_or_404(ClientePJ, pk=pk)
    form = ClientePJForm(instance=clientePJ)
    contato_forms = ContatoInlineFormSet(
        queryset=form.instance.contatos.all()
    )

    if request.method == "POST":
        form = ClientePJForm(request.POST, instance=clientePJ)
        contato_forms = ContatoInlineFormSet(
            request.POST,
            queryset=form.instance.contatos.all()
        )
        if form.is_valid() and contato_forms.is_valid():
            form.save()
            instances = contato_forms.save(commit=False)
            for obj in instances:
                obj.pessoa = clientePJ
                obj.save()
            for obj in contato_forms.deleted_objects:
                obj.delete()
            messages.success(request, 'Cliente(PJ) alterado com sucesso!')
            return redirect('cliente:listar_clientesPJ')
    template_name = 'cliente/editar_clientePJ.html'
    context = {
        'form': form,
        'formset': contato_forms,
        'title': 'Editar cliente (PJ): "%s"' % (clientePJ)
    }
    return render(request, template_name, context)


def excluir_clientePJ(request, pk):
    clientePJ = get_object_or_404(ClientePJ, pk=pk)

    if request.method == "POST":
        clientePJ.delete()
        messages.success(request, 'Cliente(PJ) excluído com sucesso!')
        return redirect('cliente:listar_clientesPJ')
    template_name = 'confirmar_delete.html'
    context = {
        'objeto': clientePJ,
        'title': 'Excluir cliente',
        'mensagem': 'Tem certeza que quer deletar o Cliente (PJ): ',
        'clientePJ': True
    }
    return render(request, template_name, context)


def listar_clientesPF(request):
    atualizado_em = datetime.now()
    clientes = ClientePF.objects.all()
    template_name = 'cliente/listar_clientesPF.html'
    context = {
        'clientes': clientes,
        'atualizado_em': atualizado_em
    }
    return render(request, template_name, context)


def novo_clientePF(request):
    form = ClientePFForm()
    contato_forms = ContatoInlineFormSet(
        queryset=Contato.objects.none()
    )

    if request.method == "POST":
        form = ClientePFForm(request.POST)
        contato_forms = ContatoInlineFormSet(
            request.POST,
            queryset=Contato.objects.none()
        )
        if form.is_valid() and contato_forms.is_valid():
            clientePF = form.save(commit=False)
            clientePF.save()
            contatos = contato_forms.save(commit=False)
            for contato in contatos:
                contato.pessoa = clientePF
                contato.save()
            messages.success(request, 'Cliente(PF) salvo com sucesso!')
            return redirect('cliente:listar_clientesPF')
    template_name = 'cliente/editar_clientePF.html'
    context = {
        'form': form,
        'formset': contato_forms,
        'title': 'Registrar cliente (PF)'
    }
    return render(request, template_name, context)


def editar_clientePF(request, pk):
    clientePF = get_object_or_404(ClientePF, pk=pk)
    form = ClientePFForm(instance=clientePF)
    contato_forms = ContatoInlineFormSet(
        queryset=form.instance.contatos.all()
    )

    if request.method == "POST":
        form = ClientePFForm(request.POST, instance=clientePF)
        contato_forms = ContatoInlineFormSet(
            request.POST,
            queryset=form.instance.contatos.all()
        )
        if form.is_valid() and contato_forms.is_valid():
            form.save()
            instances = contato_forms.save(commit=False)
            for obj in instances:
                obj.pessoa = clientePF
                obj.save()
            for obj in contato_forms.deleted_objects:
                obj.delete()
            messages.success(request, 'Cliente(PF) alterado com sucesso!')
            return redirect('cliente:listar_clientesPF')
    template_name = 'cliente/editar_clientePF.html'
    context = {
        'form': form,
        'formset': contato_forms,
        'title': 'Editar cliente (PF): "%s"' % (clientePF)
    }
    return render(request, template_name, context)


def excluir_clientePF(request, pk):
    clientePF = get_object_or_404(ClientePF, pk=pk)

    if request.method == "POST":
        clientePF.delete()
        messages.success(request, 'Cliente(PF) excluído com sucesso!')
        return redirect('cliente:listar_clientesPF')
    template_name = 'confirmar_delete.html'
    context = {
        'objeto': clientePF,
        'title': 'Excluir cliente',
        'mensagem': 'Tem certeza que quer deletar o Cliente (PF): ',
        'clientePF': True
    }
    return render(request, template_name, context)

bcrsilva/cliente/templates/cliente/editar_clientePF.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <div class="card card-register mx-auto" style="max-width: 100%;">
    <div class="card-header"><b>{{ title }}</b></div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-row">
          <div class="form-group col-md-4">
            {{ form.nome.label_tag }}
            {{ form.nome }}
            {{ form.nome.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.apelido.label_tag }}
            {{ form.apelido }}
            {{ form.apelido.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.cpf.label_tag }}
            {{ form.cpf }}
            {{ form.cpf.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.rg.label_tag }}
            {{ form.rg }}
            {{ form.rg.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.data_nascimento.label_tag }}
            {{ form.data_nascimento }}
            {{ form.data_nascimento.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.cep.label_tag }}
            {{ form.cep }}
            {{ form.cep.errors }}
          </div>
          <div class="form-group col-md-4">
            {{ form.endereco.label_tag }}
            {{ form.endereco }}
            {{ form.endereco.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.numero.label_tag }}
            {{ form.numero }}
            {{ form.numero.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.bairro.label_tag }}
            {{ form.bairro }}
            {{ form.bairro.errors }}
          </div>
          <div class="form-group col-md-3">
            {{ form.cidade.label_tag }}
            {{ form.cidade }}
            {{ form.cidade.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.uf.label_tag }}
            {{ form.uf }}
            {{ form.uf.errors }}
          </div>
        </div>

        {{ formset.management_form }}

          <div class="card card-register mx-auto" style="max-width: 100%; margin-bottom: 1em;">
            <div class="card-header"><b>Contato(s)</b></div>
            <div class="card-body">
              <div class="form-row">
                {% for form in formset %}
                  {{ form.id }}
                  <div class="form-group" style="width: 45%; margin-right: 10px;">
                    {{ form.email.label_tag }}
  			            {{ form.email }}
  			            {{ form.email.errors }}
                  </div>
                  <div class="form-group" style="width: 45%; margin-right: 10px;">
  									{{ form.telefone.label_tag }}
  			            {{ form.telefone }}
  			            {{ form.telefone.errors }}
                  </div>
                  <div class="form-group" style="margin-top: 3%;">
                    {{ form.DELETE.label }}
                    {{ form.DELETE }}
                    <!-- <a style="border: none; margin-top: 2em;" class="form-control" href="#"
                      title="Excluir">
                      <i class="fa fa-trash-o fa-lg"></i>
                    </a> -->
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        <button type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-secondary" href="{% url 'cliente:listar_clientesPF' %}">Voltar</a>
      </form>
    </div>
  </div>
{% endblock %}

bcrsilva/cliente/templates/cliente/editar_clientePJ.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <div class="card card-register mx-auto" style="max-width: 100%;">
    <div class="card-header"><b>{{ title }}</b></div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-row">
          <div class="form-group col-md-4">
            {{ form.razao_social.label_tag }}
            {{ form.razao_social }}
            {{ form.razao_social.errors }}
          </div>
          <div class="form-group col-md-4">
            {{ form.nome_fantasia.label_tag }}
            {{ form.nome_fantasia }}
            {{ form.nome_fantasia.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.cnpj.label_tag }}
            {{ form.cnpj }}
            {{ form.cnpj.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.inscricao_estadual.label_tag }}
            {{ form.inscricao_estadual }}
            {{ form.inscricao_estadual.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.cep.label_tag }}
            {{ form.cep }}
            {{ form.cep.errors }}
          </div>
          <div class="form-group col-md-4">
            {{ form.endereco.label_tag }}
            {{ form.endereco }}
            {{ form.endereco.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.numero.label_tag }}
            {{ form.numero }}
            {{ form.numero.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.bairro.label_tag }}
            {{ form.bairro }}
            {{ form.bairro.errors }}
          </div>
          <div class="form-group col-md-3">
            {{ form.cidade.label_tag }}
            {{ form.cidade }}
            {{ form.cidade.errors }}
          </div>
          <div class="form-group col-md-1">
            {{ form.uf.label_tag }}
            {{ form.uf }}
            {{ form.uf.errors }}
          </div>
        </div>

        {{ formset.management_form }}

          <div class="card card-register mx-auto" style="max-width: 100%; margin-bottom: 1em;">
            <div class="card-header"><b>Contato(s)</b></div>
            <div class="card-body">
              <div class="form-row">
                {% for form in formset %}
                  {{ form.id }}
                  <div class="form-group" style="width: 45%; margin-right: 10px;">
                    {{ form.email.label_tag }}
  			            {{ form.email }}
  			            {{ form.email.errors }}
                  </div>
                  <div class="form-group" style="width: 45%; margin-right: 10px;">
  									{{ form.telefone.label_tag }}
  			            {{ form.telefone }}
  			            {{ form.telefone.errors }}
                  </div>
                  <div class="form-group" style="margin-top: 3%;">
                    {{ form.DELETE.label }}
                    {{ form.DELETE }}
                    <!-- <a style="border: none; margin-top: 2em;" class="form-control" href="#"
                      title="Excluir">
                      <i class="fa fa-trash-o fa-lg"></i>
                    </a> -->
                  </div>
                {% endfor %}
              </div>
            </div>
          </div>
        <button type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-secondary" href="{% url 'cliente:listar_clientesPJ' %}">Voltar</a>
      </form>
    </div>
  </div>
{% endblock %}

bcrsilva/cliente/templates/cliente/listar_clientesPF.html
{% extends "base.html" %}

{% block content %}
<div class="card mb-3">
  <div class="card-header" style="height: 65px;">
    <div class="form-row" style="height: 40px;">
      <div class="form-group col-md-11" style="padding-top: 6px;">
        <i class="fa fa-table fa-lg"></i> <b>Clientes registrados (PF)</b>
      </div>
      <div class="form-group col-md-1" style="padding-left: 30px;">
        <a class="btn btn-success" href="{% url 'cliente:novo_clientePF' %}" title="Novo Cliente (Pessoa Física)">
          <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Apelido</th>
              <th>CPF</th>
              <th>Cidade</th>
              <th>Contato(s)</th>
              <th style="text-align: center; width: 13%;">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for cliente in clientes %}
              <tr>
                <td>{{ cliente.nome }}</td>
                <td>{{ cliente.apelido }}</td>
                <td>{{ cliente.cpf }}</td>
                <td>{{ cliente.cidade }}</td>
                <td>
                  {% for contato in cliente.contatos.all %}
                    {{ contato }} <br>
                  {% endfor %}
                </td>
                <!-- <td style="text-align: center;">{{ produto.preco_anterior|default_if_none:"-" }}</td> -->
                <td>
                  <div class="container">
                    <div class="row">
                      <div class="col">
                        <a href="{% url 'cliente:editar_clientePF' cliente.id %}"
                          title="Editar">
                          <i class="fa fa-pencil fa-lg"></i>
                        </a>
                      </div>
                      <div class="col">
                        <a href="{% url 'cliente:excluir_clientePF' cliente.id %}"
                          title="Excluir">
                          <i class="fa fa-trash-o fa-lg"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em {{ atualizado_em }}</div>
  </div>
{% endblock %}

bcrsilva/cliente/templates/cliente/listar_clientesPJ.html
{% extends "base.html" %}

{% block content %}
<div class="card mb-3">
  <div class="card-header" style="height: 65px;">
    <div class="form-row" style="height: 40px;">
      <div class="form-group col-md-11" style="padding-top: 6px;">
        <i class="fa fa-table fa-lg"></i> <b>Clientes registrados (PJ)</b>
      </div>
      <div class="form-group col-md-1" style="padding-left: 30px;">
        <a class="btn btn-success" href="{% url 'cliente:novo_clientePJ' %}" title="Novo Cliente (Pessoa Jurídica)">
          <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Razão Social</th>
              <th>Nome Fantasia</th>
              <th>CNPJ</th>
              <th>Cidade</th>
              <th>Contato(s)</th>
              <th style="text-align: center; width: 13%;">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for cliente in clientes %}
              <tr>
                <td>{{ cliente.razao_social }}</td>
                <td>{{ cliente.nome_fantasia }}</td>
                <td>{{ cliente.cnpj }}</td>
                <td>{{ cliente.cidade }}</td>
                <td>
                  {% for contato in cliente.contatos.all %}
                    {{ contato }} <br>
                  {% endfor %}
                </td>
                <!-- <td style="text-align: center;">{{ produto.preco_anterior|default_if_none:"-" }}</td> -->
                <td>
                  <div class="container">
                    <div class="row">
                      <div class="col">
                        <a href="{% url 'cliente:editar_clientePJ' cliente.id %}"
                          title="Editar">
                          <i class="fa fa-pencil fa-lg"></i>
                        </a>
                      </div>
                      <div class="col">
                        <a href="{% url 'cliente:excluir_clientePJ' cliente.id %}"
                          title="Excluir">
                          <i class="fa fa-trash-o fa-lg"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em {{ atualizado_em }}</div>
  </div>
{% endblock %}