bcrsilva/produto/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^novo/$', views.novo_produto, name='novo_produto'),
    url(r'^editar/(?P<pk>\d+)/$', views.editar_produto, name='editar_produto'),
    url(r'^excluir/(?P<pk>\d+)/$', views.excluir_produto, name='excluir_produto'),
    url(r'^categoria/$', views.lista_categorias, name="lista_categorias"),
    url(r'^categoria/(?P<pk>\d+)/$',
        views.detalhes_categoria, name='detalhes_categoria'),
    url(r'^categoria/nova/$', views.nova_categoria, name='nova_categoria'),
    url(r'^categoria/editar/(?P<pk>\d+)/$',
        views.editar_categoria, name='editar_categoria'),
    url(r'^categoria/excluir/(?P<pk>\d+)/$',
        views.excluir_categoria, name='excluir_categoria'),
]

bcrsilva/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('bcrsilva.core.urls', namespace="core")),
    url(r'^cliente/', include('bcrsilva.cliente.urls', namespace="cliente")),
    url(r'^produto/', include('bcrsilva.produto.urls', namespace="produto")),
    url(r'^fornecedor/', include('bcrsilva.fornecedor.urls', namespace="fornecedor")),
    url(r'^estoque/', include('bcrsilva.estoque.urls', namespace="estoque")),
    url(r'^admin/', include(admin.site.urls)),
]

bcrsilva/produto/models.py
from django.db import models
from model_utils import FieldTracker


class Categoria(models.Model):
    nome = models.CharField('Nome', max_length=100)
    descricao = models.TextField('Descrição', blank=True)
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['nome']


class Produto(models.Model):
    nome = models.CharField('Nome', max_length=100)
    descricao = models.TextField('Descrição', blank=True)
    preco_anterior = models.DecimalField(
        'Preço anterior', max_digits=7, decimal_places=2,
        blank=True, null=True, editable=False
    )

    preco_custo = models.DecimalField(
        'Preço de custo', max_digits=7, decimal_places=2
    )

    preco_venda = models.DecimalField(
        'Preço de venda', max_digits=7, decimal_places=2
    )
    lucro = models.DecimalField(
        'Lucro %', max_digits=5, decimal_places=2, editable=False
    )
    unidade_medida_choices = (
        ('ml', 'mililitro'),
        ('l', 'litro'),
        ('mm', 'milímetro'),
        ('cm', 'centímetro'),
        ('m', 'metro'),
        ('mg', 'miligrama'),
        ('g', 'grama'),
        ('kg', 'quilograma'),
        ('un', 'unidade'),
        ('cx', 'caixa'),
        ('pc', 'pacote'),
        ('sc', 'saco'),
        ('p', 'par')
    )
    unidade_medida = models.CharField(
        'Unidade de medida',
        max_length=2,
        choices=unidade_medida_choices
    )

    multiplo = models.DecimalField('Múltiplo', max_digits=7, decimal_places=2)
    ncm = models.CharField('NCM', max_length=20)
    categoria = models.ForeignKey(Categoria, verbose_name='Categoria',
                                  related_name='produtos',
                                  on_delete=models.CASCADE
                                  )
    criado_em = models.DateTimeField('Criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('Atualizado em', auto_now=True)

    tracker = FieldTracker()

    def save(self, *args, **kwargs):
        self.lucro = (
            ((self.preco_venda - self.preco_custo) * 100) / self.preco_custo
        )
        if self.tracker.has_changed('preco_venda'):
            self.preco_anterior = self.tracker.previous('preco_venda')
            super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['nome']

bcrsilva/produto/forms.py
from django import forms
from .models import Categoria, Produto


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome', 'descricao']

        widgets = {
            'nome': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Insira o nome'
                }
            ),
            'descricao': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Descreva a categoria',
                    'style': 'resize: none',
                    'rows': 5
                }
            )
        }

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = '__all__'

bcrsilva/produto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from datetime import datetime
from .models import Categoria, Produto
from .forms import CategoriaForm, ProdutoForm


def home(request):
    atualizado_em = datetime.now()
    produtos = Produto.objects.all()
    template_name = 'produto/home.html'
    context = {
        'produtos': produtos,
        'atualizado_em': atualizado_em
    }
    return render(request, template_name, context)


def novo_produto(request):
    if request.method == "POST":
        form = ProdutoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto salvo com sucesso!')
            return redirect('produto:home')
    else:
        form = ProdutoForm()
    template_name = 'produto/editar_produto.html'
    context = {
        'form': form,
        'title': 'Registrar produto'
    }
    return render(request, template_name, context)


def editar_produto(request, pk):
    produto = get_object_or_404(Produto, pk=pk)
    if request.method == "POST":
        form = ProdutoForm(request.POST, instance=produto)
        if form.is_valid():
            form.save()
            messages.success(request, 'Produto alterado com sucesso!')
            return redirect('produto:home')
    else:
        form = ProdutoForm(instance=produto)
    template_name = 'produto/editar_produto.html'
    context = {
        'form': form,
        'title': 'Editar produto: "%s"' % (produto)
    }
    return render(request, template_name, context)


def excluir_produto(request, pk):
    produto = get_object_or_404(Produto, pk=pk)

    if request.method == "POST":
        produto.delete()
        messages.success(request, 'Produto excluído com sucesso!')
        return redirect('produto:home')
    template_name = 'confirmar_delete.html'
    context = {
        'objeto': produto,
        'title': 'Excluir produto',
        'mensagem': 'Tem certeza que quer deletar o Produto: ',
        'produto': True
    }
    return render(request, template_name, context)


def lista_categorias(request):
    atualizado_em = datetime.now()
    categorias = Categoria.objects.all()
    template_name = 'produto/lista_categorias.html'
    context = {
        'categorias': categorias,
        'atualizado_em': atualizado_em
    }
    return render(request, template_name, context)


def detalhes_categoria(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk)
    template_name = 'produto/detalhes_categoria.html'
    context = {
        'categoria': categoria
    }
    return render(request, template_name, context)


def nova_categoria(request):
    if request.method == "POST":
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria salva com sucesso!')
            return redirect('produto:lista_categorias')
    else:
        form = CategoriaForm()
    template_name = 'produto/editar_categoria.html'
    context = {
        'form': form,
        'title': 'Registrar categoria'
    }
    return render(request, template_name, context)


def editar_categoria(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk)
    if request.method == "POST":
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            form.save()
            messages.success(request, 'Categoria alterada com sucesso!')
            return redirect('produto:lista_categorias')
    else:
        form = CategoriaForm(instance=categoria)
    template_name = 'produto/editar_categoria.html'
    context = {
        'form': form,
        'title': 'Editar categoria: "%s"' % (categoria)
    }
    return render(request, template_name, context)


def excluir_categoria(request, pk):
    categoria = get_object_or_404(Categoria, pk=pk)

    if request.method == "POST":
        categoria.delete()
        messages.success(request, 'Categoria excluída com sucesso!')
        return redirect('produto:lista_categorias')
    template_name = 'confirmar_delete.html'
    context = {
        'objeto': categoria,
        'title': 'Excluir categoria',
        'mensagem': 'Tem certeza que quer deletar a Categoria: ',
        'categoria': True
    }
    return render(request, template_name, context)

bcrsilva/produto/templates/produto/detalhes_categoria.html
{% extends "base.html" %}

{% block content %}
{{ categoria }}
{% endblock %}

bcrsilva/produto/templates/produto/editar_categoria.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <div class="card card-register mx-auto" style="max-width: 50%;">
    <div class="card-header"><b>{{ title }}</b></div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
          {{ form.nome.label_tag }}
          {{ form.nome }}
          <!-- {% render_field form.nome class+="form-control" placeholder+="Insira o nome" %} -->
          {{ form.nome.errors }}
        </div>
        <div class="form-group">
          {{ form.descricao.label_tag }}
          {{ form.descricao }}
          <!-- {% render_field form.descricao class+="form-control" style+="resize: none" rows="5" placeholder+="Descreva a categoria" %} -->
          {{ form.nome.errors }}
        </div>
        <button type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-secondary" href="{% url 'produto:lista_categorias' %}">Voltar</a>
      </form>
    </div>
  </div>
{% endblock %}

bcrsilva/produto/templates/produto/editar_produto.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
  <div class="card card-register mx-auto" style="max-width: 80%;">
    <div class="card-header"><b>{{ title }}</b></div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-row">
          <div class="form-group col-md-4">
            {{ form.categoria.label_tag }}
            {% render_field form.categoria class+="form-control" %}
            {{ form.categoria.errors }}
          </div>
          <!-- <div>
            <a class="btn btn-success" href="{% url 'produto:nova_categoria' %}"
              title="Novo produto" style="margin-top: 32px;">
              <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
            </a>
          </div> -->
          <div class="form-group col-md-6">
            {{ form.nome.label_tag }}
            {% render_field form.nome class+="form-control" placeholder+="Informe o nome" %}
            {{ form.nome.errors }}
          </div>
          <div class="form-group col-md-2">
            {{ form.ncm.label_tag }}
            {% render_field form.ncm class+="form-control" placeholder+="Informe o NCM" %}
            {{ form.ncm.errors }}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            {{ form.descricao.label_tag }}
            {% render_field form.descricao class+="form-control" style+="resize: none" rows="5" placeholder+="Descreva o produto" %}
            {{ form.descricao.errors }}
          </div>
          <div class="form-row col-md-6" style="margin-left: 5px;">
            <div class="form-group col-md-6">
              {{ form.preco_custo.label_tag }}
              {% render_field form.preco_custo class+="form-control" placeholder+="Informe o custo" style+="margin-bottom: 26px" %}
              {{ form.preco_custo.errors }}

              {{ form.unidade_medida.label_tag }}
              {% render_field form.unidade_medida class+="form-control" %}
              {{ form.unidade_medida.errors }}
            </div>
            <div class="form-group col-md-6">
              {{ form.preco_venda.label_tag }}
              {% render_field form.preco_venda class+="form-control" placeholder+="Informe o custo" style+="margin-bottom: 26px" %}
              {{ form.preco_venda.errors }}

              {{ form.multiplo.label_tag }}
              {% render_field form.multiplo class+="form-control" %}
              {{ form.multiplo.errors }}
            </div>
          </div>
        </div>
        <button type="submit" class="btn btn-success">Salvar</button>
        <a class="btn btn-secondary" href="{% url 'produto:home' %}">Voltar</a>
      </form>
    </div>
  </div>
{% endblock %}

bcrsilva/produto/templates/produto/home.html
{% extends "base.html" %}

{% block content %}
<div class="card mb-3">
  <div class="card-header" style="height: 65px;">
    <div class="form-row" style="height: 40px;">
      <div class="form-group col-md-11" style="padding-top: 6px;">
        <i class="fa fa-table fa-lg"></i> <b>Produtos registrados</b>
      </div>
      <div class="form-group col-md-1" style="padding-left: 30px;">
        <a class="btn btn-success" href="{% url 'produto:novo_produto' %}" title="Novo produto">
          <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Categoria</th>
              <th>Nome</th>
              <th style="text-align: center; width: 12%;">Preço Anterior(R$)</th>
              <th style="text-align: center; width: 8%;">Preço (R$)</th>
              <th style="text-align: center; width: 8%;">Lucro (%)</th>
              <th style="text-align: center; width: 13%;">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for produto in produtos %}
              <tr>
                <td>{{ produto.categoria }}</td>
                <td>{{ produto.nome }}</td>
                <td style="text-align: center;">{{ produto.preco_anterior|default_if_none:"-" }}</td>
                <td style="text-align: center;">{{ produto.preco_venda }}</td>
                <td style="text-align: center;">{{ produto.lucro }}</td>
                <td>
                  <div class="container">
                    <div class="row">
                      <div class="col">
                        <a href="{% url 'produto:editar_produto' produto.id %}"
                          title="Editar">
                          <i class="fa fa-pencil fa-lg"></i>
                        </a>
                      </div>
                      <div class="col">
                        <a href="{% url 'produto:excluir_produto' produto.id %}"
                          title="Excluir">
                          <i class="fa fa-trash-o fa-lg"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em {{ atualizado_em }}</div>
  </div>
{% endblock %}

bcrsilva/produto/templates/produto/lista_categorias.html
{% extends "base.html" %}

{% block content %}
<div class="card mb-3">
  <div class="card-header" style="height: 65px;">
    <div class="form-row" style="height: 40px;">
      <div class="form-group col-md-11" style="padding-top: 6px;">
        <i class="fa fa-table fa-lg"></i> <b>Categorias registradas</b>
      </div>
      <div class="form-group col-md-1" style="padding-left: 30px;">
        <a class="btn btn-success" href="{% url 'produto:nova_categoria' %}" title="Nova categoria">
          <i class="fa fa-plus fa-lg" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Descrição</th>
              <th style="width: 30%;">Última alteração</th>
              <th style="width: 14%;">Ações</th>
            </tr>
          </thead>
          <!-- <tfoot>
            <tr>
              <th>Nome</th>
              <th>Descrição</th>
              <th>Última alteração</th>
              <th>Ações</th>
            </tr>
          </tfoot> -->
          <tbody>
            {% for categoria in categorias %}
              <tr>
                <td>{{ categoria.nome }}</td>
                <td>{{ categoria.descricao }}</td>
                <td>{{ categoria.atualizado_em }}</td>
                <td>
                  <div class="container">
                    <div class="row">
                      <div class="col">
                        <a href="{% url 'produto:editar_categoria' categoria.id %}"
                          title="Editar">
                          <i class="fa fa-pencil fa-lg"></i>
                        </a>
                      </div>
                      <div class="col">
                        <a href="{% url 'produto:excluir_categoria' categoria.id %}"
                          title="Excluir">
                          <i class="fa fa-trash-o fa-lg"></i>
                        </a>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em {{ atualizado_em }}</div>
  </div>
{% endblock %}